### ISSUE TITLE
Unexpected ranks when running evaluate_performance on RandomBaseline model

### ISSUE THREAD

**Issue by lordstar** [Accenture/AmpliGraph#94] opened 2019-05-29 14:40 UTC
### Description

When running evaluate_performance on a RandomBaseline model, the ranks returned for all triples are in the range of 1-5. Accordingly, hits@n is equal to 1 for almost all choices of n.

### Steps to Reproduce

<img width="830" alt="hitsat_ranks" src="https://user-images.githubusercontent.com/3476287/58566618-ded03300-8228-11e9-837e-365115bdc6f9.png">

**Comment by sumitpai** [comment] 2019-05-30 08:54
Thanks for pointing it out. I guess this bug got introduced in out previous release when we added a default evaluation mode. We will fix this quickly and release a patch soon.

**Comment by sumitpai** [comment] 2019-05-31 12:45
The issue is fixed on develop branch and would be fixed on master in the next release

**Closed** 2019-06-07 08:06 UTC
Labels: bug
