### ISSUE TITLE
Trained relation embeddings in TransE model different sizes

### ISSUE THREAD

**Issue by NetherNova** [Accenture/AmpliGraph#174] opened 2020-02-10 12:30 UTC
### Description
After training TransE embeddings on a E x R x E dataset. When accessing the `model.trained_model_params[1].shape` is not |R| x k, but much more relation embeddings than actual relations.

`model.rel_to_idx` contains the correct set of |R| relations.

Is this expected behavior, i.e. does `model.trained_model_params[1]` contain duplicated relation embeddings due to some optimizations for batch processing?

### Actual Behavior
`model.trained_model_params[1].shape` !=  |R| x k

### Expected Behavior
`model.trained_model_params[1].shape` ==  |R| x k

### Steps to Reproduce

```
triples = load_from_csv('./', 'edgetensor.csv', sep=',', header=0)
model = TransE(batches_count=128, seed=555, epochs=5, k=32, loss='pairwise', loss_params={'margin': 1},
                   verbose=True, optimizer='sgd', optimizer_params={'lr': 0.01})
model.fit(X_train)
model.trained_model_params[1].shape
```

**Comment by sumitpai** [comment] 2020-02-10 14:28
I tried to reproduce this with 3 datasets. However, the outputs were correct. 

```
def fit(X):
    model = TransE(batches_count=10, seed=0, epochs=2, k=30, eta=10)
    model.fit(X['train'])
    print('Shapes:{} for entities, {} for relations'.format(model.trained_model_params[0].shape, 
                                                            model.trained_model_params[1].shape))


fit(load_wn18rr())
fit(load_fb15k_237())
fit(load_yago3_10())
```
Outputs:

```
Shapes:(40559, 30) for entities, (11, 30) for relations
Shapes:(14505, 30) for entities, (237, 30) for relations
Shapes:(123143, 30) for entities, (37, 30) for relations
​```

Can you please verify if the number of unique relations in csv that you load match the model.trained_model_params[1].shape[0]

**Comment by NetherNova** [comment] 2020-02-10 14:50
```
triples = load_from_csv('./', 'edgetensor.csv', sep=',', header=0)

triples.shape
(18753212, 3)

len(np.unique(triples[:, 1]))
87

model.trained_model_params[1].shape
(293018, 32)

model.trained_model_params[0].shape
(6572623, 32)
```

I just saw that it seems to be connected to the number of entities in each batch somehow:

> WARNING - Your graph has a large number of distinct entities. Found 6572623 distinct entities
> WARNING - Changing the variable initialization strategy.
> WARNING - Changing the strategy to use lazy loading of variables...
> WARNING - Only 293018 embeddings would be loaded in memory per batch...

Broadcasting issue maybe?

**Comment by sumitpai** [comment] 2020-02-10 15:55
This seems to be a bug with the large graph mode. Thanks for pointing this out. The issue seems to be with initialisation of the embedding matrices. It is initialized as batch_size *2. 

For entity embeddings, the original matrix is stored on cpu and only the entity embeddings of the entities in the batches are loaded as required (hence batch_size *2, self.internal_k). Whereas for relations, the embeddings are always placed on GPU (so this should be len(self.rel_to_idx), self.internal_k). 

So while initializing the embedding matrices, it should be as follows:
```
self.ent_emb = tf.get_variable('ent_emb', shape=[self.batch_size * 2, self.internal_k],
                                           initializer=self.initializer.get_tf_initializer(), dtype=tf.float32)
self.rel_emb = tf.get_variable('rel_emb', shape=[len(self.rel_to_idx), self.internal_k],
                                           initializer=self.initializer.get_tf_initializer(), dtype=tf.float32)
```

With the current initialization:
```
self.rel_emb = tf.get_variable('rel_emb', shape=[self.batch_size * 2, self.internal_k],
                                           initializer=self.initializer.get_tf_initializer(), dtype=tf.float32)
```
we are creating extra relations which are never used/trained. I just did a quick test to check this hypothesis. In your case, since you have only 87 relations, only these 87 would be used during training. During training, only those 87 rows of the self.rel_emb matrix would be affected. the rest would remain unchanged. So, for now, you can look at the first 87 rows(embeddings) of the  self.rel_emb, until we fix the issue and release it on the main branch. Thanks again for finding this bug in the large graph mode.

**Comment by sumitpai** [comment] 2020-02-10 17:13
Issue is fixed on developed. 

Previously, in large graph mode, we were initializing rel_emb matrix with some additional (invalid) relations which were never used/learnt during training.  We verified this by looking at the values before and after training for unused relations. They were unchanged. 

We fixed this issue by fixing the _initialize_parameters() function which initialized the sizes of the embedding matrices.

**Closed** 2020-02-24 13:04 UTC
Labels: bug
