### ISSUE TITLE
handling small number of relations

### ISSUE THREAD

**Issue by Chen-Cai-OSU** [Accenture/AmpliGraph#125] opened 2019-08-11 12:17 UTC
Hello,

I am experimenting on some synthetic data where there are only small number of relations. In that case, if the number of relations is too small (say 2), train/valid/test split may not guarantee that every entity in the test data also appears in the training data, and this will result in the following error.

`ERROR - KG - Failed after 0:00:08!
Traceback (most recent calls WITHOUT Sacred internals):
  File "play.py", line 142, in main
    'corrupt_side': 's+o'  # corrupt subject and object (but not at once)
  File "/home/cai.507/Documents/DeepLearning/AmpliGraph-master/ampligraph/latent_features/ComplEx.py", line 372, in fit
    super().fit(X, early_stopping, early_stopping_params, model_name=self.name)
  File "/home/cai.507/Documents/DeepLearning/AmpliGraph-master/ampligraph/latent_features/models.py", line 714, in fit
    self._initialize_early_stopping()
  File "/home/cai.507/Documents/DeepLearning/AmpliGraph-master/ampligraph/latent_features/models.py", line 513, in _initialize_early_stopping
    self.x_valid = to_idx(self.x_valid, ent_to_idx=self.ent_to_idx, rel_to_idx=self.rel_to_idx)
  File "/home/cai.507/Documents/DeepLearning/AmpliGraph-master/ampligraph/evaluation/protocol.py", line 469, in to_idx
    return _convert_to_idx(X, ent_to_idx, rel_to_idx, ent_to_idx)
  File "/home/cai.507/Documents/DeepLearning/AmpliGraph-master/ampligraph/evaluation/protocol.py", line 417, in _convert_to_idx
    x_idx_s = np.vectorize(ent_to_idx.get)(X[:, 0])
  File "/home/cai.507/anaconda3/envs/ampligraph/lib/python3.7/site-packages/numpy/lib/function_base.py", line 2091, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "/home/cai.507/anaconda3/envs/ampligraph/lib/python3.7/site-packages/numpy/lib/function_base.py", line 2170, in _vectorize_call
    res = array(outputs, copy=False, subok=True, dtype=otypes[0])
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
`

My question is that is there some elegant way to handle this? Right now, I will make sure the number of relations is above 5 but I really want to perform some careful control study and restrict the number of relations to be very small, say 2 or 3.  

Do you have some suggestions?

Thank you!

**Comment by sumitpai** [comment] 2019-08-12 10:26
Have you tried using the function train_test_split_no_unseen in the module ampligraph.evaluation to generate the test set? This can be used to create a train/test set which dont have disjoint entities. I would suggest you to use this as of now.

We are also working on another issue where we would like to approximate the embeddings of unseen entities at test time. The issue is under development (#82 ) and may be released in 1.2 release. You can follow it on that branch and we will notify you when it is completed.

**Closed** 2020-02-14 11:12 UTC
Labels: duplicate, question
