### ISSUE TITLE
Implementations of more models?

### ISSUE THREAD

**Issue by Hao-666** [Accenture/AmpliGraph#254] opened 2021-07-08 02:27 UTC
Hi, I am wondering could this library provide implementations of more models like TransR, RotatE etc.? The implemented models now seem a little bit limited and therefore the comparison between more models cannot be conducted in it. This library is handy and awesome, really want to conduct tasks in it:). Thanks.

**Comment by sumitpai** [comment] 2021-07-08 13:21
We have an implementation of RotatE on a branch (feature/8), however, since with our implementation, we couldnt reproduce the performance as reported in the paper we have not merged it with master.

**Comment by Hao-666** [comment] 2021-07-08 15:15
Hi @sumitpai 

Thanks for your reply. So are the implementations of more models in the plan?

**Comment by sumitpai** [comment] 2021-07-08 15:19
None for now. We have not come across any new models which show considerable performance improvements on the standard datasets.

Do you have any suggestions and reason to include them? When we plan to add more, we will definitely consider them.

**Comment by Hao-666** [comment] 2021-07-08 15:29
@sumitpai  I see. Thanks.

Not actually, just wondering :)

**Closed** 2021-07-08 15:29 UTC
